apiVersion: v2
name: vanisec
description: A Helm chart for Vanisec - Secure Secret Sharing
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - vanisec
  - secret
  - one-time
  - clouddrove
  - redis
maintainers:
  - name: CloudDrove Team
home: https://github.com/clouddrove/vanisec
sources:
  - https://github.com/clouddrove/vanisec

