name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
        env:
          CI: true

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Build application
        run: npm run build
        env:
          REDIS_URL: redis://localhost:6379/3

